name: CI - Linux - ROS
on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, BUILDER: catkin_tools}
          - {ROS_DISTRO: rolling}
          - {ROS_DISTRO: jazzy}
          - {ROS_DISTRO: iron}
          - {ROS_DISTRO: humble}
    env:
      CCACHE_DIR: /github/home/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}
      - uses: 'ros-industrial/industrial_ci@16472786c1ffc53596007da4318db98d1f677933'
        env: ${{ matrix.env }}
