name: Release on PyPI

on:
  push:
    tags:
      - "v*"

env:
  CMEEL_LOG_LEVEL: DEBUG

jobs:
  linux:
    name: "${{ matrix.image }} ${{ matrix.arch }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        image: ["manylinux2014", "musllinux_1_1"]
        arch: ["x86_64"]
        include:
          - image: "manylinux_2_28"
            arch: "aarch64"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - run: python -m pip install -U pip
      - run: python -m pip install cmeel
      - run: python -m cmeel docker -Ui "quay.io/pypa/${{ matrix.image }}_${{ matrix.arch }}"
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  macos:
    name: "macos"
    runs-on: "macos-10.15"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: python -m pip wheel -vw wh .
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  release:
    needs: ["linux", "macos"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v3
      - run: python -m pip install twine
      - run: python -m twine upload -u __token__ -p "${{ secrets.PYPI_TOKEN }}" artifact/eiquadprog*.yml
